//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWdEEBudget.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BudgetBuilding_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetBuilding_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWdEEBudget.App_LocalResources.BudgetBuilding.aspx", typeof(BudgetBuilding_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपादित करा.
        /// </summary>
        public static string Button1Resource1_Text {
            get {
                return ResourceManager.GetString("Button1Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Button1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Button1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रद्द करा.
        /// </summary>
        public static string Button2Resource1_Text {
            get {
                return ResourceManager.GetString("Button2Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Button2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Button2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ddlTypeResource1_ToolTip {
            get {
                return ResourceManager.GetString("ddlTypeResource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList10Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList10Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList11Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList11Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList12Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList12Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList13Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList13Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList14Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList14Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList15Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList15Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList16Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList16Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList17Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList17Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList18Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList18Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList19Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList19Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList20Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList20Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList21Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList21Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList22Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList22Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList23Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList23Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList24Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList24Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList25Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList25Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList26Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList26Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList27Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList27Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList28Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList28Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList29Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList29Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList3Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList3Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList4Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList4Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList5Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList5Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList6Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList6Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList7Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList7Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList8Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList8Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DropDownList9Resource1_ToolTip {
            get {
                return ResourceManager.GetString("DropDownList9Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label1Resource1_Text {
            get {
                return ResourceManager.GetString("Label1Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Label1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("Label1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource1_Text {
            get {
                return ResourceManager.GetString("ListItemResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource1_Value {
            get {
                return ResourceManager.GetString("ListItemResource1.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जुलै.
        /// </summary>
        public static string ListItemResource10_Text {
            get {
                return ResourceManager.GetString("ListItemResource10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जुलै.
        /// </summary>
        public static string ListItemResource10_Value {
            get {
                return ResourceManager.GetString("ListItemResource10.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource11_Text {
            get {
                return ResourceManager.GetString("ListItemResource11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource11_Value {
            get {
                return ResourceManager.GetString("ListItemResource11.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  डिसेंबर.
        /// </summary>
        public static string ListItemResource12_Text {
            get {
                return ResourceManager.GetString("ListItemResource12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  डिसेंबर.
        /// </summary>
        public static string ListItemResource12_Value {
            get {
                return ResourceManager.GetString("ListItemResource12.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource13_Text {
            get {
                return ResourceManager.GetString("ListItemResource13.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource13_Value {
            get {
                return ResourceManager.GetString("ListItemResource13.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource14_Text {
            get {
                return ResourceManager.GetString("ListItemResource14.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource14_Value {
            get {
                return ResourceManager.GetString("ListItemResource14.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ४/२०१६.
        /// </summary>
        public static string ListItemResource15_Text {
            get {
                return ResourceManager.GetString("ListItemResource15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ४/२०१६.
        /// </summary>
        public static string ListItemResource15_Value {
            get {
                return ResourceManager.GetString("ListItemResource15.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource16_Text {
            get {
                return ResourceManager.GetString("ListItemResource16.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  २०१६-२०१७.
        /// </summary>
        public static string ListItemResource16_Value {
            get {
                return ResourceManager.GetString("ListItemResource16.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च-२०१६.
        /// </summary>
        public static string ListItemResource17_Text {
            get {
                return ResourceManager.GetString("ListItemResource17.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च-२०१६.
        /// </summary>
        public static string ListItemResource17_Value {
            get {
                return ResourceManager.GetString("ListItemResource17.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च.
        /// </summary>
        public static string ListItemResource18_Text {
            get {
                return ResourceManager.GetString("ListItemResource18.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च.
        /// </summary>
        public static string ListItemResource18_Value {
            get {
                return ResourceManager.GetString("ListItemResource18.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  जून-जुलै २०१६.
        /// </summary>
        public static string ListItemResource19_Text {
            get {
                return ResourceManager.GetString("ListItemResource19.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  जून-जुलै २०१६.
        /// </summary>
        public static string ListItemResource19_Value {
            get {
                return ResourceManager.GetString("ListItemResource19.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource2_Text {
            get {
                return ResourceManager.GetString("ListItemResource2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource2_Value {
            get {
                return ResourceManager.GetString("ListItemResource2.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  डिसेंबर २०१६.
        /// </summary>
        public static string ListItemResource20_Text {
            get {
                return ResourceManager.GetString("ListItemResource20.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  डिसेंबर २०१६.
        /// </summary>
        public static string ListItemResource20_Value {
            get {
                return ResourceManager.GetString("ListItemResource20.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७ .
        /// </summary>
        public static string ListItemResource21_Text {
            get {
                return ResourceManager.GetString("ListItemResource21.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७ .
        /// </summary>
        public static string ListItemResource21_Value {
            get {
                return ResourceManager.GetString("ListItemResource21.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७ .
        /// </summary>
        public static string ListItemResource22_Text {
            get {
                return ResourceManager.GetString("ListItemResource22.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७ .
        /// </summary>
        public static string ListItemResource22_Value {
            get {
                return ResourceManager.GetString("ListItemResource22.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जून-२०१६.
        /// </summary>
        public static string ListItemResource23_Text {
            get {
                return ResourceManager.GetString("ListItemResource23.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जून-२०१६.
        /// </summary>
        public static string ListItemResource23_Value {
            get {
                return ResourceManager.GetString("ListItemResource23.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सप्टेंबर-२०१६.
        /// </summary>
        public static string ListItemResource24_Text {
            get {
                return ResourceManager.GetString("ListItemResource24.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सप्टेंबर-२०१६.
        /// </summary>
        public static string ListItemResource24_Value {
            get {
                return ResourceManager.GetString("ListItemResource24.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डिसेंबर-२०१६.
        /// </summary>
        public static string ListItemResource25_Text {
            get {
                return ResourceManager.GetString("ListItemResource25.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डिसेंबर-२०१६.
        /// </summary>
        public static string ListItemResource25_Value {
            get {
                return ResourceManager.GetString("ListItemResource25.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource26_Text {
            get {
                return ResourceManager.GetString("ListItemResource26.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource26_Value {
            get {
                return ResourceManager.GetString("ListItemResource26.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जून-२०१६.
        /// </summary>
        public static string ListItemResource27_Text {
            get {
                return ResourceManager.GetString("ListItemResource27.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जून-२०१६.
        /// </summary>
        public static string ListItemResource27_Value {
            get {
                return ResourceManager.GetString("ListItemResource27.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सप्टेंबर-२०१६.
        /// </summary>
        public static string ListItemResource28_Text {
            get {
                return ResourceManager.GetString("ListItemResource28.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सप्टेंबर-२०१६.
        /// </summary>
        public static string ListItemResource28_Value {
            get {
                return ResourceManager.GetString("ListItemResource28.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डिसेंबर-२०१६.
        /// </summary>
        public static string ListItemResource29_Text {
            get {
                return ResourceManager.GetString("ListItemResource29.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डिसेंबर-२०१६.
        /// </summary>
        public static string ListItemResource29_Value {
            get {
                return ResourceManager.GetString("ListItemResource29.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुणे.
        /// </summary>
        public static string ListItemResource3_Text {
            get {
                return ResourceManager.GetString("ListItemResource3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुणे.
        /// </summary>
        public static string ListItemResource3_Value {
            get {
                return ResourceManager.GetString("ListItemResource3.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource30_Text {
            get {
                return ResourceManager.GetString("ListItemResource30.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource30_Value {
            get {
                return ResourceManager.GetString("ListItemResource30.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१७-२०१८.
        /// </summary>
        public static string ListItemResource31_Text {
            get {
                return ResourceManager.GetString("ListItemResource31.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१७-२०१८.
        /// </summary>
        public static string ListItemResource31_Value {
            get {
                return ResourceManager.GetString("ListItemResource31.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource32_Text {
            get {
                return ResourceManager.GetString("ListItemResource32.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource32_Value {
            get {
                return ResourceManager.GetString("ListItemResource32.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सार्वजनिक आरोग्य विभाग.
        /// </summary>
        public static string ListItemResource33_Text {
            get {
                return ResourceManager.GetString("ListItemResource33.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सार्वजनिक आरोग्य विभाग.
        /// </summary>
        public static string ListItemResource33_Value {
            get {
                return ResourceManager.GetString("ListItemResource33.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सार्वजनिक बांधकाम विभाग.
        /// </summary>
        public static string ListItemResource34_Text {
            get {
                return ResourceManager.GetString("ListItemResource34.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सार्वजनिक बांधकाम विभाग.
        /// </summary>
        public static string ListItemResource34_Value {
            get {
                return ResourceManager.GetString("ListItemResource34.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to महसूल व वन विभाग.
        /// </summary>
        public static string ListItemResource35_Text {
            get {
                return ResourceManager.GetString("ListItemResource35.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to महसूल व वन विभाग.
        /// </summary>
        public static string ListItemResource35_Value {
            get {
                return ResourceManager.GetString("ListItemResource35.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource36_Text {
            get {
                return ResourceManager.GetString("ListItemResource36.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......निवडा........
        /// </summary>
        public static string ListItemResource36_Value {
            get {
                return ResourceManager.GetString("ListItemResource36.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुंबई.
        /// </summary>
        public static string ListItemResource4_Text {
            get {
                return ResourceManager.GetString("ListItemResource4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मुंबई.
        /// </summary>
        public static string ListItemResource4_Value {
            get {
                return ResourceManager.GetString("ListItemResource4.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सातारा.
        /// </summary>
        public static string ListItemResource5_Text {
            get {
                return ResourceManager.GetString("ListItemResource5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सातारा.
        /// </summary>
        public static string ListItemResource5_Value {
            get {
                return ResourceManager.GetString("ListItemResource5.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource6_Text {
            get {
                return ResourceManager.GetString("ListItemResource6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मार्च-२०१६.
        /// </summary>
        public static string ListItemResource6_Value {
            get {
                return ResourceManager.GetString("ListItemResource6.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to १-४-२०१६.
        /// </summary>
        public static string ListItemResource7_Text {
            get {
                return ResourceManager.GetString("ListItemResource7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to १-४-२०१६.
        /// </summary>
        public static string ListItemResource7_Value {
            get {
                return ResourceManager.GetString("ListItemResource7.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७.
        /// </summary>
        public static string ListItemResource8_Text {
            get {
                return ResourceManager.GetString("ListItemResource8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to २०१६-२०१७.
        /// </summary>
        public static string ListItemResource8_Value {
            get {
                return ResourceManager.GetString("ListItemResource8.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च-२०१६.
        /// </summary>
        public static string ListItemResource9_Text {
            get {
                return ResourceManager.GetString("ListItemResource9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  मार्च-२०१६.
        /// </summary>
        public static string ListItemResource9_Value {
            get {
                return ResourceManager.GetString("ListItemResource9.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEPwdEastPuneBudget.
        /// </summary>
        public static string PageResource1_Title {
            get {
                return ResourceManager.GetString("PageResource1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox10Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox10Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox10Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox10Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox11Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox11Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox11Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox11Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox12Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox12Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox12Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox12Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox13Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox13Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox13Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox13Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox14Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox14Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox14Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox14Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox15Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox15Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox15Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox15Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox16Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox16Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox16Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox16Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox17Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox17Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox17Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox17Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox18Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox18Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox18Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox18Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox19Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox19Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox19Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox19Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox1Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox1Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox1Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox1Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox20Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox20Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox20Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox20Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox22Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox22Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox22Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox22Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox24Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox24Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox24Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox24Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox26Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox26Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox26Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox26Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox28Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox28Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox28Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox28Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox2Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox2Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox2Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox2Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox30Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox30Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox30Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox30Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox31Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox31Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox31Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox31Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox32Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox32Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox32Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox32Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox33Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox33Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox33Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox33Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox34Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox34Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox34Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox34Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox35Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox35Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox35Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox35Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox36Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox36Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox36Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox36Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox37Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox37Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox37Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox37Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox38Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox38Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox38Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox38Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox39Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox39Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox39Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox39Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox3Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox3Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox3Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox3Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox40Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox40Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox40Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox40Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox41Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox41Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox41Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox41Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox42Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox42Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox42Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox42Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox43Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox43Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox43Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox43Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox44Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox44Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox44Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox44Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox45Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox45Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox45Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox45Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox46Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox46Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox46Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox46Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox47Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox47Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox47Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox47Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox4Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox4Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox4Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox4Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox5Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox5Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox5Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox5Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox66Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox66Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox66Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox66Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox6Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox6Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox6Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox6Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox7Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox7Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox7Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox7Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox8Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox8Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox8Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox8Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox9Resource1_Text {
            get {
                return ResourceManager.GetString("TextBox9Resource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextBox9Resource1_ToolTip {
            get {
                return ResourceManager.GetString("TextBox9Resource1.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string txtMobileNoResource1_Text {
            get {
                return ResourceManager.GetString("txtMobileNoResource1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string txtMobileNoResource1_ToolTip {
            get {
                return ResourceManager.GetString("txtMobileNoResource1.ToolTip", resourceCulture);
            }
        }
    }
}
