<%@ Page Title="" Language="C#" MasterPageFile="~/SuperAdmin.Master" AutoEventWireup="true" CodeBehind="ViewUserProfile.aspx.cs" Inherits="PWdEEBudget.ViewUserProfile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        th {
            color: white;
            text-align: center;
        }
    </style>
    <style type="text/css">
        .GridPager a,
        .GridPager span {
            display: inline-block;
            padding: 0px 9px;
            margin-right: 4px;
            border-radius: 3px;
            border: solid 1px #c0c0c0;
            background: #e9e9e9;
            box-shadow: inset 0px 1px 0px rgba(255,255,255, .8), 0px 1px 3px rgba(0,0,0, .1);
            font-size: .875em;
            font-weight: bold;
            text-decoration: none;
            color: #717171;
            text-shadow: 0px 1px 0px rgba(255,255,255, 1);
        }

        .GridPager a {
            background-color: #f5f5f5;
            color: #969696;
            border: 1px solid #969696;
        }

        .GridPager span {
            background: #616161;
            box-shadow: inset 0px 0px 8px rgba(0,0,0, .5), 0px 1px 0px rgba(255,255,255, .8);
            color: #f0f0f0;
            text-shadow: 0px 0px 3px rgba(0,0,0, .5);
            border: 1px solid #3AC0F2;
        }
        .btnBack {
            background: linear-gradient(#010101,#db0e10)!important;
            height: 15%;
            float: right;
            border-radius: 50%!important;
        }
    </style>
    <style>
        @media only screen and (min-width:768px) {
            /*desktop*/

        }

        @media only screen and (max-width:500px) {

            .btnform {
                height: 28px !important;
                width: 32% !important;
            }
           
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:UpdatePanel ID="UpdatePanel2" runat="server">
        <ContentTemplate>
            <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
            <div style="overflow-x: auto">
                <table id="Table2" class="table table-bordered">
                    <tr>
                        <th>Select Post :-
                            <asp:DropDownList runat="server" ID="ddlPost1" AutoPostBack="true" OnSelectedIndexChanged="ddlPost1_SelectedIndexChanged"></asp:DropDownList>
                        </th>
                        <th>
                              <asp:ImageButton runat="server" ID="btnBack" ImageUrl="~/logo/Go-back.ico" AlternateText="Back" CssClass="btnBack"  OnClientClick="JavaScript:window.history.back(1); return false;" />
                       
                        </th>
                    </tr>
                    <tr>
                        <td style="text-align: center" colspan="2">
                            <asp:GridView runat="server" ID="grdvUserAdmin" AllowPaging="True"
                                PageSize="100" OnPageIndexChanging="grdvUserAdmin_PageIndexChanging"
                                BorderStyle="Solid" BorderWidth="1px" Width="100%" AutoGenerateColumns="False"
                                Font-Names="Arial" Font-Size="11pt" HeaderStyle-BackColor="#2c3e50" CaptionAlign="Top"
                                AutoGenerateEditButton="True" OnRowEditing="grdvUserAdmin_RowEditing"
                                OnRowCancelingEdit="grdvUserAdmin_RowCancelingEdit"
                                OnRowUpdating="grdvUserAdmin_RowUpdating" AutoGenerateDeleteButton="true" OnRowDeleting="grdvUserAdmin_RowDeleting" OnRowDataBound="grdvUserAdmin_RowDataBound">
                                <EditRowStyle BackColor="Gray" BorderColor="Red" ForeColor="Yellow" />
                                <%--<AlternatingRowStyle BackColor="LightGray"></AlternatingRowStyle>--%>
                                <Columns>

                                    <asp:TemplateField HeaderText="NO">

                                        <EditItemTemplate>
                                            <asp:Label BorderStyle="Ridge" ID="lblId" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Name">
                                        <EditItemTemplate>
                                            <asp:TextBox runat="server" ID="txtName" Text='<%# Bind("Name") %>'></asp:TextBox>
                                            <asp:Label ID="oldNamelbl" runat="server" Text='<%# Bind("Name") %>' Visible="false"></asp:Label>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label5" runat="server" Style="float: left;" Text='<%# Bind("Name") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Mobile No">
                                        <EditItemTemplate>
                                            <asp:TextBox runat="server" ID="txtMobile" Text='<%# Bind("MobileNo") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label6" runat="server" Style="float: left;" Text='<%# Bind("MobileNo") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Email Id">
                                        <EditItemTemplate>
                                            <asp:TextBox runat="server" ID="txtEmail" Text='<%# Bind("Email") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label7" runat="server" Style="float: left;" Text='<%# Bind("Email") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Post">
                                        <EditItemTemplate>
                                            <asp:HiddenField ID="hdnPost" runat="server" Value='<%#Eval("Post") %>' />
                                            <asp:DropDownList runat="server" ID="DDLPost" >
                                               <%-- <asp:ListItem>Executive Engineer</asp:ListItem>
                                                <asp:ListItem>Deputy Executive Engineer</asp:ListItem>
                                                <asp:ListItem> Deputy Engineer</asp:ListItem>
                                                <asp:ListItem>Sectional Engineer</asp:ListItem>
                                                <asp:ListItem>Junior Engineer</asp:ListItem>
                                                <asp:ListItem>Assistant Engineer Class-1</asp:ListItem>
                                                <asp:ListItem>Assistant Engineer Class-2</asp:ListItem>
                                                <asp:ListItem>Divisional Accountant</asp:ListItem>
                                                <asp:ListItem>Senior Auditer</asp:ListItem>
                                                <asp:ListItem>Senior Clerk</asp:ListItem>
                                                <asp:ListItem>Junior Clerk</asp:ListItem>
                                                <asp:ListItem>Contractor</asp:ListItem>
                                                <asp:ListItem>MLA</asp:ListItem>
                                                <asp:ListItem>MLA</asp:ListItem>
                                                <asp:ListItem>Others</asp:ListItem>--%>
                                            </asp:DropDownList>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="lblPost" runat="server" Style="float: left;" Text='<%# Bind("Post") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="User Id">
                                        <EditItemTemplate>
                                            <asp:TextBox runat="server" ID="txtUserId" Text='<%# Bind("UserId") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label9" runat="server" Style="float: left;" Text='<%# Bind("UserId") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>

                                    <asp:TemplateField HeaderText="Password">
                                        <EditItemTemplate>
                                            <asp:TextBox runat="server" ID="txtPassword" Text='<%# Bind("Password") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                        <ItemTemplate>
                                            <asp:Label ID="Label10" runat="server" Style="float: left;" Text='<%# Bind("Password") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                                <EmptyDataTemplate>

                                    <h1 style="background-color: #D3D3D3">No Data Found</h1>
                                </EmptyDataTemplate>
                                <PagerStyle HorizontalAlign="Center" CssClass="GridPager" ForeColor="Black" />
                                <HeaderStyle BackColor="#2C3E50"></HeaderStyle>
                            </asp:GridView>
                        </td>
                    </tr>

                </table>
            </div>
           <%-- <asp:Button ID="Button4" runat="server" Text="Back" CssClass="btn btn-primary btnform" Height="40px" Width="100px" OnClick="Button4_Click" />
            <asp:Button ID="Button1" runat="server" Text="View" CssClass="btn btn-info btnform" Height="40px" Width="100px" OnClientClick="PrintGrid()" />
            <asp:Button ID="btnSendMail" runat="server" OnClick="btnSendMail_Click" class="btn btn-warning btnform" Height="40px" Width="100px" Text="Send Mail" />--%>
           

        </ContentTemplate>
    </asp:UpdatePanel>

    <script lang="javascript" type="text/javascript">

        function PrintGrid() {
            var prtGrid = document.getElementById('Print');
            prtGrid.border = 0;
            var prtwin = window.open('', 'PrintGridViewData', 'left=0,top=0,width=1000,height=1000,tollbar=0,scrollbars=1,status=0,resizable=1');
            prtwin.document.write(prtGrid.outerHTML);

        }
    </script>

</asp:Content>
